"""Data Quality Check code generation for Iceberg tables.

Generates Impala SQL, Trino SQL, and CDE PySpark scripts for running quality checks.
Results are stored in an Iceberg results table (default.dq_metric_results), following
Snowflake's DATA_METRIC_FUNCTION_RESULTS pattern.
"""

from typing import Any, Optional
import time
from datetime import datetime, timedelta

# ============================================================================
# DQ Results Cache - In-memory cache with TTL to avoid repeated Impala queries
# ============================================================================
class DQResultsCache:
    """Simple in-memory cache for DQ results with TTL (time-to-live)."""

    def __init__(self, ttl_seconds: int = 1800):
        """Initialize cache.

        Args:
            ttl_seconds: Time-to-live in seconds (default 30 minutes)
        """
        self.cache = {}
        self.ttl_seconds = ttl_seconds

    def get(self, key: str) -> Optional[Any]:
        """Get value from cache if it exists and hasn't expired."""
        if key not in self.cache:
            return None

        value, timestamp = self.cache[key]
        if time.time() - timestamp > self.ttl_seconds:
            # Expired, remove it
            del self.cache[key]
            return None

        return value

    def set(self, key: str, value: Any) -> None:
        """Store value in cache with current timestamp."""
        self.cache[key] = (value, time.time())

    def invalidate(self, key: str) -> None:
        """Remove specific key from cache."""
        if key in self.cache:
            del self.cache[key]

    def clear_all(self) -> None:
        """Clear entire cache."""
        self.cache.clear()

    def stats(self) -> dict:
        """Return cache statistics."""
        return {
            "total_keys": len(self.cache),
            "ttl_seconds": self.ttl_seconds,
            "keys": list(self.cache.keys())
        }

# Global cache instance
_dq_cache = DQResultsCache(ttl_seconds=1800)  # 30 minutes


def invalidate_dq_cache(table_name: str) -> None:
    """Invalidate DQ results cache for a specific table.

    Call this after running new quality checks to force fresh fetch next time.

    Args:
        table_name: Table name to invalidate cache for
    """
    cache_key = f"dq_results:{table_name}"
    _dq_cache.invalidate(cache_key)
    print(f"[DQ] Cache invalidated for {table_name}")


def get_dq_cache_stats() -> dict:
    """Get cache statistics."""
    return _dq_cache.stats()


def generate_quality_check_code(table_name: str, fields: list[dict[str, Any]], run_id: Optional[str] = None, engine: str = 'impala') -> dict[str, str]:
    """Generate quality check code templates.

    Args:
        table_name: Fully qualified table name (e.g., 'demo.customers') or Kafka topic name
        fields: List of field dicts with 'name', 'type', 'required' keys from describe_iceberg_table() or Kafka schema
        run_id: Optional UUID for correlating all checks in this run (generated if not provided)
        engine: 'impala', 'trino', 'spark' for Iceberg tables; 'flink' for Kafka topics

    Returns:
        Dict with keys: impala_sql/flink_sql, trino_sql, spark_script, results_table, run_id
    """
    import uuid
    if not run_id:
        run_id = str(uuid.uuid4())

    if engine == 'flink':
        return {
            "flink_sql": _build_flink_sql(table_name, fields, run_id),
            "results_table": "quality_results",
            "run_id": run_id,
        }
    else:
        return {
            "impala_sql": _build_impala_sql(table_name, fields, run_id),
            "trino_sql": _build_trino_sql(table_name, fields, run_id),
            "spark_script": _build_spark_script(table_name, fields, run_id),
            "results_table": "default.dq_metric_results",
            "run_id": run_id,
        }


def _build_impala_sql(table_name: str, fields: list[dict[str, Any]], run_id: str) -> str:
    """Generate Impala SQL for quality checks.

    Impala-specific notes:
    - Uses STORED AS ICEBERG syntax
    - Uses provided run_id for all checks in this run (correlates results)
    - now() for timestamp
    - CAST(... AS DOUBLE) for type conversion
    - CONCAT for string operations
    """
    field_names = [f["name"] for f in fields]

    sql_lines = [
        f"-- Data Quality Check: {table_name}",
        "-- Generated by Cloudera AI Agents | Run in Cloudera Impala (Hue)",
        f"-- Run ID: {run_id}",
        "-- Results stored in: default.dq_metric_results",
        "",
        "CREATE TABLE IF NOT EXISTS default.dq_metric_results (",
        "  run_id STRING, run_timestamp TIMESTAMP, table_name STRING,",
        "  check_name STRING, column_name STRING, metric_value DOUBLE,",
        "  metric_label STRING, status STRING, threshold_warn DOUBLE,",
        "  threshold_fail DOUBLE, engine STRING",
        ") STORED AS ICEBERG",
        "LOCATION 's3a://iceberg-warehouse/warehouse/default.db/dq_metric_results';",
        "",
        "-- Step 1: Volume check",
        f"INSERT INTO default.dq_metric_results",
        f"SELECT",
        f"  '{run_id}' AS run_id, now() AS run_timestamp, '{table_name}' AS table_name,",
        f"  'volume' AS check_name, NULL AS column_name, CAST(COUNT(*) AS DOUBLE) AS metric_value,",
        f"  CONCAT(CAST(COUNT(*) AS STRING), ' rows') AS metric_label,",
        f"  'info' AS status, NULL AS threshold_warn, NULL AS threshold_fail, 'impala' AS engine",
        f"FROM {table_name};",
        "",
    ]

    # Completeness checks for each column
    sql_lines.append("-- Step 2: Completeness checks (NULL% per column)")
    for col_name in field_names:
        sql_lines.append("")
        sql_lines.append(f"INSERT INTO default.dq_metric_results")
        sql_lines.append(f"SELECT")
        sql_lines.append(f"  '{run_id}' AS run_id, now() AS run_timestamp, '{table_name}' AS table_name,")
        sql_lines.append(f"  'completeness' AS check_name, '{col_name}' AS column_name,")
        # NULL % calculation - use backticks to quote column names
        sql_lines.append(f"  CAST((COUNT(*) - COUNT(`{col_name}`)) AS DOUBLE) / CAST(COUNT(*) AS DOUBLE) * 100 AS metric_value,")
        sql_lines.append(f"  CONCAT(CAST(ROUND(CAST((COUNT(*) - COUNT(`{col_name}`)) AS DOUBLE) / CAST(COUNT(*) AS DOUBLE) * 100, 1) AS STRING), '% null') AS metric_label,")
        # Status logic
        sql_lines.append(f"  CASE WHEN CAST((COUNT(*) - COUNT(`{col_name}`)) AS DOUBLE) / CAST(COUNT(*) AS DOUBLE) * 100 < 5 THEN 'pass'")
        sql_lines.append(f"       WHEN CAST((COUNT(*) - COUNT(`{col_name}`)) AS DOUBLE) / CAST(COUNT(*) AS DOUBLE) * 100 < 20 THEN 'warn'")
        sql_lines.append(f"       ELSE 'fail' END AS status,")
        sql_lines.append(f"  5.0 AS threshold_warn, 20.0 AS threshold_fail, 'impala' AS engine")
        sql_lines.append(f"FROM {table_name};")

    return "\n".join(sql_lines)


def _build_trino_sql(table_name: str, fields: list[dict[str, Any]], run_id: str) -> str:
    """Generate Trino SQL for quality checks.

    Trino-specific notes:
    - Uses WITH (format = 'ICEBERG') or Iceberg catalog syntax
    - current_timestamp instead of now()
    - Uses provided run_id for all checks in this run (correlates results)
    - Different string functions
    """
    field_names = [f["name"] for f in fields]

    sql_lines = [
        f"-- Data Quality Check: {table_name}",
        "-- Generated by Cloudera AI Agents | Run in Cloudera Trino",
        "-- Results stored in: default.dq_metric_results",
        "",
        "CREATE TABLE IF NOT EXISTS default.dq_metric_results (",
        "  run_id VARCHAR, run_timestamp TIMESTAMP, table_name VARCHAR,",
        "  check_name VARCHAR, column_name VARCHAR, metric_value DOUBLE,",
        "  metric_label VARCHAR, status VARCHAR, threshold_warn DOUBLE,",
        "  threshold_fail DOUBLE, engine VARCHAR",
        ") WITH (format = 'ICEBERG', location = 's3a://iceberg-warehouse/warehouse/default.db/dq_metric_results');",
        "",
        "-- Step 1: Volume check",
        f"INSERT INTO default.dq_metric_results",
        f"SELECT",
        f"  CAST('{run_id}' AS VARCHAR) AS run_id, current_timestamp AS run_timestamp, '{table_name}' AS table_name,",
        f"  'volume' AS check_name, NULL AS column_name, CAST(COUNT(*) AS DOUBLE) AS metric_value,",
        f"  CONCAT(CAST(COUNT(*) AS VARCHAR), ' rows') AS metric_label,",
        f"  'info' AS status, NULL AS threshold_warn, NULL AS threshold_fail, 'trino' AS engine",
        f"FROM \"{table_name}\";",
        "",
    ]

    # Completeness checks for each column
    sql_lines.append("-- Step 2: Completeness checks (NULL% per column)")
    for col_name in field_names:
        sql_lines.append("")
        sql_lines.append(f"INSERT INTO default.dq_metric_results")
        sql_lines.append(f"SELECT")
        sql_lines.append(f"  CAST('{run_id}' AS VARCHAR) AS run_id, current_timestamp AS run_timestamp, '{table_name}' AS table_name,")
        sql_lines.append(f"  'completeness' AS check_name, '{col_name}' AS column_name,")
        sql_lines.append(f"  CAST((COUNT(*) - COUNT(\"{col_name}\")) AS DOUBLE) / CAST(COUNT(*) AS DOUBLE) * 100 AS metric_value,")
        sql_lines.append(f"  CONCAT(CAST(ROUND(CAST((COUNT(*) - COUNT(\"{col_name}\")) AS DOUBLE) / CAST(COUNT(*) AS DOUBLE) * 100, 1) AS VARCHAR), '% null') AS metric_label,")
        sql_lines.append(f"  CASE WHEN CAST((COUNT(*) - COUNT(\"{col_name}\")) AS DOUBLE) / CAST(COUNT(*) AS DOUBLE) * 100 < 5 THEN 'pass'")
        sql_lines.append(f"       WHEN CAST((COUNT(*) - COUNT(\"{col_name}\")) AS DOUBLE) / CAST(COUNT(*) AS DOUBLE) * 100 < 20 THEN 'warn'")
        sql_lines.append(f"       ELSE 'fail' END AS status,")
        sql_lines.append(f"  5.0 AS threshold_warn, 20.0 AS threshold_fail, 'trino' AS engine")
        sql_lines.append(f"FROM \"{table_name}\";")

    return "\n".join(sql_lines)


def _build_spark_script(table_name: str, fields: list[dict[str, Any]], run_id: str) -> str:
    """Generate CDE PySpark script for quality checks.

    Compatible with Spark 3.x and Iceberg 1.x in CDP runtime.
    Uses PySpark DataFrame API for completeness checks.
    Correlates all checks in this run using provided run_id.
    """
    field_names = [f["name"] for f in fields]

    script_lines = [
        "# Data Quality Check: " + table_name,
        "# Generated by Cloudera AI Agents | Submit as CDE Job",
        "# Compatible: CDP Runtime, Spark 3.x, Iceberg 1.x",
        "",
        "from pyspark.sql import SparkSession",
        "from pyspark.sql import functions as F",
        "from pyspark.sql.types import (",
        "    StructType, StructField, StringType,",
        "    DoubleType, TimestampType, NullType",
        ")",
        "import uuid",
        "from datetime import datetime",
        "",
        "spark = SparkSession.builder \\",
        "    .config('spark.sql.extensions',",
        "            'org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions') \\",
        "    .config('spark.sql.catalog.spark_catalog',",
        "            'org.apache.iceberg.spark.SparkCatalog') \\",
        "    .config('spark.sql.catalog.spark_catalog.type', 'rest') \\",
        "    .getOrCreate()",
        "",
        f"TABLE_NAME = '{table_name}'",
        f"RUN_ID = '{run_id}'",
        "RUN_TIME = datetime.now()",
        "",
        "# Create results table if not exists",
        "spark.sql('''",
        "CREATE TABLE IF NOT EXISTS default.dq_metric_results (",
        "  run_id STRING, run_timestamp TIMESTAMP, table_name STRING,",
        "  check_name STRING, column_name STRING, metric_value DOUBLE,",
        "  metric_label STRING, status STRING, threshold_warn DOUBLE,",
        "  threshold_fail DOUBLE, engine STRING",
        ") USING ICEBERG",
        "LOCATION 's3a://iceberg-warehouse/warehouse/default.db/dq_metric_results'",
        "''')",
        "",
        "# Read source table",
        "df = spark.table(TABLE_NAME)",
        "total = df.count()",
        "results = []",
        "",
        "# Volume check",
        "results.append({",
        "    'check_name': 'volume',",
        "    'column_name': None,",
        "    'metric_value': float(total),",
        "    'metric_label': f'{total:,} rows',",
        "    'status': 'info',",
        "    'threshold_warn': None,",
        "    'threshold_fail': None",
        "})",
        "",
        "# Completeness checks per column",
    ]

    for col_name in field_names:
        script_lines.append(f"null_ct = df.filter(F.col('`{col_name}`').isNull()).count()")
        script_lines.append(f"pct = round((null_ct / total * 100), 2) if total > 0 else 0.0")
        script_lines.append(f"status = 'pass' if pct < 5 else ('warn' if pct < 20 else 'fail')")
        script_lines.append(f"results.append({{")
        script_lines.append(f"    'check_name': 'completeness',")
        script_lines.append(f"    'column_name': '{col_name}',")
        script_lines.append(f"    'metric_value': pct,")
        script_lines.append(f"    'metric_label': f'{{pct:.1f}}% null',")
        script_lines.append(f"    'status': status,")
        script_lines.append(f"    'threshold_warn': 5.0,")
        script_lines.append(f"    'threshold_fail': 20.0")
        script_lines.append(f"}})")
        script_lines.append("")

    script_lines.extend([
        "# Build result rows",
        "rows = [{'run_id': RUN_ID, 'run_timestamp': RUN_TIME, 'table_name': TABLE_NAME,",
        "         'engine': 'spark', **r} for r in results]",
        "",
        "# Schema for results",
        "RESULT_SCHEMA = StructType([",
        "    StructField('run_id', StringType()),",
        "    StructField('run_timestamp', TimestampType()),",
        "    StructField('table_name', StringType()),",
        "    StructField('check_name', StringType()),",
        "    StructField('column_name', StringType()),",
        "    StructField('metric_value', DoubleType()),",
        "    StructField('metric_label', StringType()),",
        "    StructField('status', StringType()),",
        "    StructField('threshold_warn', DoubleType()),",
        "    StructField('threshold_fail', DoubleType()),",
        "    StructField('engine', StringType()),",
        "])",
        "",
        "# Write results to Iceberg",
        "spark.createDataFrame(rows, RESULT_SCHEMA).writeTo('default.dq_metric_results').append()",
        "print(f'✅ Quality check complete. Run ID: {RUN_ID}. {len(results)} checks written.')",
    ])

    return "\n".join(script_lines)


def _build_flink_sql(topic_name: str, fields: list[dict[str, Any]], run_id: str) -> str:
    """Generate Flink SQL for quality checks on Kafka topics.

    Flink-specific notes:
    - Reads from Kafka source
    - Validates schema and freshness
    - Writes results to Kafka sink or files
    - Compatible with Apache Flink SQL
    """
    field_names = [f["name"] for f in fields]
    field_types = {f["name"]: f.get("type", "STRING") for f in fields}

    sql_lines = [
        f"-- Data Quality Check: {topic_name}",
        "-- Generated by Cloudera AI Agents | Run in Apache Flink SQL",
        f"-- Run ID: {run_id}",
        "-- Results published to Kafka quality_results topic or file sink",
        "",
        "-- Step 1: Define Kafka source table",
        f"CREATE TABLE `{topic_name}_source` (",
        "  event_time TIMESTAMP(3) METADATA FROM 'timestamp',",
    ]

    # Add fields
    for field in fields:
        field_name = field["name"]
        field_type = field.get("type", "STRING").upper()
        # Map Avro types to Flink types
        flink_type = _map_avro_to_flink_type(field_type)
        sql_lines.append(f"  `{field_name}` {flink_type},")

    sql_lines.extend([
        "  WATERMARK FOR event_time AS event_time - INTERVAL '5' SECOND",
        ") WITH (",
        "  'connector' = 'kafka',",
        "  'topic' = '" + topic_name + "',",
        "  'properties.bootstrap.servers' = 'localhost:9092',",
        "  'format' = 'avro',",
        f"  'avro.schema' = '{_build_avro_schema(field_names, field_types)}'",
        ");",
        "",
        "-- Step 2: Schema validation check",
        f"SELECT",
        f"  '{run_id}' AS run_id,",
        f"  CURRENT_TIMESTAMP AS run_timestamp,",
        f"  '{topic_name}' AS topic_name,",
        f"  'schema_validation' AS check_name,",
        f"  COUNT(*) AS total_records,",
        f"  COUNT(CASE WHEN {' IS NOT NULL AND '.join([f'`{n}`' for n in field_names])} THEN 1 END) AS complete_records,",
        f"  ROUND(COUNT(CASE WHEN {' IS NOT NULL AND '.join([f'`{n}`' for n in field_names])} THEN 1 END) * 100.0 / COUNT(*), 2) AS completeness_pct,",
        f"  MAX(event_time) AS last_event_time",
        f"FROM `{topic_name}_source`",
        f"WHERE event_time > CURRENT_TIMESTAMP - INTERVAL '1' DAY;",
        "",
        "-- Step 3: Null field checks",
    ])

    for field_name in field_names:
        sql_lines.extend([
            f"SELECT",
            f"  '{run_id}' AS run_id,",
            f"  CURRENT_TIMESTAMP AS run_timestamp,",
            f"  '{topic_name}' AS topic_name,",
            f"  'null_check' AS check_name,",
            f"  '{field_name}' AS column_name,",
            f"  COUNT(*) AS total_records,",
            f"  COUNT(`{field_name}`) AS non_null_records,",
            f"  ROUND((COUNT(*) - COUNT(`{field_name}`)) * 100.0 / COUNT(*), 2) AS null_pct",
            f"FROM `{topic_name}_source`",
            f"WHERE event_time > CURRENT_TIMESTAMP - INTERVAL '1' HOUR;",
            "",
        ])

    return "\n".join(sql_lines)


def _map_avro_to_flink_type(avro_type: str) -> str:
    """Map Avro type names to Flink SQL type names."""
    type_map = {
        'STRING': 'STRING',
        'LONG': 'BIGINT',
        'INT': 'INT',
        'FLOAT': 'FLOAT',
        'DOUBLE': 'DOUBLE',
        'BOOLEAN': 'BOOLEAN',
        'BYTES': 'BYTES',
        'FIXED': 'BYTES',
    }
    return type_map.get(avro_type.upper(), 'STRING')


def _build_avro_schema(field_names: list[str], field_types: dict[str, str]) -> str:
    """Build a simplified Avro schema JSON string."""
    import json
    schema = {
        "type": "record",
        "fields": [
            {"name": name, "type": _map_avro_to_avro_primitive(field_types.get(name, "string"))}
            for name in field_names
        ]
    }
    return json.dumps(schema).replace('"', '\\"')


def _map_avro_to_avro_primitive(avro_type: str) -> str:
    """Map Avro type to primitive Avro type for schema."""
    type_map = {
        'STRING': 'string',
        'LONG': 'long',
        'INT': 'int',
        'FLOAT': 'float',
        'DOUBLE': 'double',
        'BOOLEAN': 'boolean',
        'BYTES': 'bytes',
        'FIXED': 'bytes',
    }
    return type_map.get(avro_type.upper(), 'string')


def get_dq_results(table_name: str, use_cache: bool = True) -> Optional[dict[str, Any]]:
    """Read latest quality check results from the DQ results table with caching.

    Args:
        table_name: Fully qualified table name (e.g., 'demo.customers')
        use_cache: Whether to use cached results if available (default True)

    Returns:
        Dict with keys: table_name, last_run, run_id, overall_score, checks
        Or None if results table doesn't exist or no results for this table.
    """
    # Check cache first. The cache stores both successful results AND the empty
    # sentinel ({"__empty__": True}) for misses, so the UI doesn't re-issue a
    # ~40s Impala connection attempt on every tab open.
    cache_key = f"dq_results:{table_name}"
    if use_cache:
        cached_result = _dq_cache.get(cache_key)
        if cached_result is not None:
            if cached_result.get("__empty__"):
                print(f"[DQ] Cache HIT (negative) for {table_name}")
                return None
            print(f"[DQ] Cache HIT for {table_name}")
            return cached_result
        print(f"[DQ] Cache MISS for {table_name}")

    def _cache_empty_and_return_none(reason: str):
        """Negative-cache the empty result for a short window so the UI doesn't replay."""
        _dq_cache.set(cache_key, {"__empty__": True, "reason": reason})
        print(f"[DQ] Cached EMPTY for {table_name}: {reason}")
        return None

    try:
        # Query results via Impala instead of PyIceberg (avoids S3 permissions issues)
        from impala.dbapi import connect as impala_connect
        from urllib.parse import urlparse
        import os

        # Connection details. The single source of truth for the Knox host is
        # KNOX_LOGIN_URL (set in .env); we parse the host out of it so callers
        # don't have to keep KNOX_HOST in sync separately. KNOX_USERNAME is the
        # canonical name; KNOX_USER kept as fallback for older configs.
        knox_login_url = os.getenv("KNOX_LOGIN_URL", "")
        knox_host = (
            os.getenv("KNOX_HOST")
            or (urlparse(knox_login_url).hostname if knox_login_url else None)
            or "localhost"
        )
        knox_user = os.getenv("KNOX_USERNAME") or os.getenv("KNOX_USER") or "admin"
        knox_pass = os.getenv("KNOX_PASSWORD", "")
        impala_http_path = os.getenv("IMPALA_HTTP_PATH", "gateway/cdp-proxy-api/impala/")
        impala_port = int(os.getenv("IMPALA_PORT", "8443"))            # Knox gateway listens on 8443
        impala_use_ssl = os.getenv("IMPALA_USE_SSL", "false").lower() == "true"  # http://...:8443 → plaintext
        connect_timeout = float(os.getenv("IMPALA_CONNECT_TIMEOUT_SECS", "8"))

        # Connect to Impala via Knox — bounded timeout so a misconfigured topology
        # fails in ~connect_timeout seconds instead of ~40s
        try:
            conn = impala_connect(
                host=knox_host,
                port=impala_port,
                use_ssl=impala_use_ssl,
                use_http_transport=True,
                http_path=impala_http_path,
                auth_mechanism='LDAP',
                user=knox_user,
                password=knox_pass,
                timeout=connect_timeout,
            )
            cursor = conn.cursor()
        except Exception as e:
            print(f"Failed to connect to Impala at {knox_host}:{impala_port}{impala_http_path}: {e}")
            return _cache_empty_and_return_none(f"connect failed: {e}")

        # Use simple WHERE clause - will match any case variation
        where_clause = f"LOWER(TRIM(table_name)) = LOWER(TRIM('{table_name}'))"

        query = f"""
        SELECT
            run_id,
            run_timestamp,
            check_name,
            column_name,
            metric_value,
            metric_label,
            status,
            threshold_warn,
            threshold_fail
        FROM default.dq_metric_results
        WHERE {where_clause}
        ORDER BY run_timestamp DESC
        """

        try:
            import logging as _log_mod
            _log = _log_mod.getLogger(__name__)
            _log.info(f"[DQ] Executing query for table '{table_name}'")
            cursor.execute(query)
            _log.info(f"[DQ] Query executed, getting metadata")
            # Manually unzip cursor results into dictionaries for JSON serialization
            col_names = [desc[0] for desc in cursor.description] if cursor.description else []
            _log.info(f"[DQ] Column names: {col_names}")
            raw_rows = cursor.fetchall()
            _log.info(f"[DQ] Fetched {len(raw_rows)} raw rows")
            rows = [dict(zip(col_names, raw_row)) for raw_row in raw_rows]
            _log.info(f"[DQ] Created {len(rows)} dict rows. First row keys: {list(rows[0].keys()) if rows else 'N/A'}")
        except Exception as e:
            print(f"Error querying results: {e}")
            return _cache_empty_and_return_none(f"query error: {e}")

        if not rows:
            print(f"No rows returned for table '{table_name}'. Columns were: {col_names}")
            return _cache_empty_and_return_none("no rows for this table")

        # Convert to DataFrame for easier manipulation
        import pandas as pd
        # Use actual columns from cursor.description instead of hardcoded list
        df = pd.DataFrame(rows)

        # Sort by run_timestamp DESC to ensure latest run is first
        df['run_timestamp'] = pd.to_datetime(df['run_timestamp'])
        df = df.sort_values('run_timestamp', ascending=False)

        # Get latest run ID from most recent timestamp
        latest_run_id = df.iloc[0]['run_id']
        run_data = df[df['run_id'] == latest_run_id]

        logger.info(f"[DQ] Total rows: {len(df)}, Latest run_id: {latest_run_id}, Filtered rows: {len(run_data)}")

        if run_data.empty:
            print(f"run_data is empty after filtering by run_id {latest_run_id}")
            return _cache_empty_and_return_none("filtered run_data empty")

        print(f"Found {len(run_data)} rows for run_id {latest_run_id}")

        # Build checks list
        checks = []
        pass_count, warn_count, fail_count = 0, 0, 0
        total_score = 0.0
        check_count = 0

        import math

        for _, row in run_data.iterrows():
            # Handle NaN values
            def to_float_or_none(val):
                if val is None:
                    return None
                try:
                    f = float(val)
                    return f if not math.isnan(f) else None
                except:
                    return None

            metric_val = to_float_or_none(row["metric_value"])
            check = {
                "check_name": str(row["check_name"]) if row["check_name"] else None,
                "column_name": str(row["column_name"]) if row["column_name"] else None,
                "metric_value": metric_val,
                "metric_label": str(row["metric_label"]) if row["metric_label"] else None,
                "status": str(row["status"]) if row["status"] else None,
            }
            threshold_warn = to_float_or_none(row["threshold_warn"]) if "threshold_warn" in row else None
            if threshold_warn is not None:
                check["threshold_warn"] = threshold_warn
            threshold_fail = to_float_or_none(row["threshold_fail"]) if "threshold_fail" in row else None
            if threshold_fail is not None:
                check["threshold_fail"] = threshold_fail

            checks.append(check)

            # Calculate overall score based on ACTUAL METRIC VALUES, not just status
            # For metrics that are percentages (completeness, volume, freshness), use the metric value
            # For binary checks, use status
            status = str(row["status"])
            if metric_val is not None and metric_val >= 0:
                # Use actual metric value (e.g., 99.0% completeness → 99.0 points)
                total_score += metric_val
            else:
                # Fallback to status-based scoring
                if status == "pass":
                    total_score += 100.0
                elif status == "warn":
                    total_score += 50.0
                elif status == "fail":
                    total_score += 0.0

            if status != "info":
                check_count += 1

        # Overall score: Average of all metric values (0-100)
        overall_score = (total_score / check_count) if check_count > 0 else 100

        # Handle timestamp - could be datetime object or string
        last_run_ts = run_data.iloc[0]["run_timestamp"]
        if hasattr(last_run_ts, 'isoformat'):
            last_run_str = last_run_ts.isoformat()
        else:
            last_run_str = str(last_run_ts)

        result = {
            "table_name": table_name,
            "last_run": last_run_str,
            "run_id": str(latest_run_id),
            "overall_score": round(overall_score, 0),
            "checks": checks,
        }

        # Store in cache before returning
        _dq_cache.set(cache_key, result)
        print(f"[DQ] Cached results for {table_name} (TTL: {_dq_cache.ttl_seconds}s)")

        return result

    except Exception as e:
        print(f"Error reading DQ results: {e}")
        return None
